name: UpdateAzureTemplateSpecs
on: 
  workflow_dispatch:

env:
  TEMPLATE_NAME: WindowsServerDatacenter2019
  RESOURCE_GROUP: rg-arm-test

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az ts create --name $TEMPLATE_NAME --version "v0.0.1" --resource-group $RESOURCE_GROUP --location "canadacentral" --template-file "azuredeploy.json"